name: Maximo Workorder Build

on:
  push:
    branches:
      - main
      - maximoworkorder

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t maximoworkorder-app ./assetmanagement.maximo.workorder/src

      - name: List Docker images
        run: docker images
