name: Click Workorder CI

on:
  push:
    paths:
      - 'assetmanagement/assetmanagement.click.workorder/**'
  pull_request:
    paths:
      - 'assetmanagement/assetmanagement.click.workorder/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Docker build
        run: docker build -t click-workorder-app ./assetmanagement/assetmanagement.click.workorder/src
